site_name: Build Tools for Aria Docs
repo_url: https://github.com/vmware/build-tools-for-vmware-aria
theme:
  name: material
  logo: assets/logo.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - search.highlight
    - search.suggest
    - search.share
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Dark Mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light Mode
extra:
  version:
    provider: mike
plugins:
  - search
  - awesome-pages
  - tags
  - mike:
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

# extra_css:
#   - css/version-select.css
# extra_javascript:
#   - js/version-select.js
