objectType: ConfigurationElement
name: Example Configuration
description: Sample Codify Configuration
version: 1.0.0
folder: ACoE/Codify
attributes:
  foo:
    type: string
    description: Foo description
  bar:
    type: SecureString
    description: Bar description
  baz:
    type: number
    description: ''
  host:
    type: REST:RESTHost
    description: 'sample REST host'
